---
- name: Check if systemd exists
  stat: path=/etc/systemd/system
  register: systemd_check

- name: Install nsqd systemd service
  template:
    src: nsqd.service.j2
    dest: /etc/systemd/system/nsqd.service
  when: systemd_check.stat.exists == true
  notify:
    - reload daemon
    - restart nsqd
